services:
  web:
    build: .
    container_name: swiftorder_app
    command: gunicorn --bind 0.0.0.0:8000 swiftorder.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: mysql:8.0
    container_name: swiftorder_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12121399D@niyal
      MYSQL_DATABASE: swiftorder_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 12121399D@niyal
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:7
    container_name: swiftorder_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql_data:
