services:
  web:
    build: .
    container_name: swiftorder_main
    command: gunicorn --bind 0.0.0.0:8000 swiftorder.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: mysql:8.0
    container_name: swiftorder_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:7
    container_name: swiftorder_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql_data:
