# Generated by Django 4.2 on 2025-01-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Waiting for Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('canceled', 'Payment Canceled')], default='waiting', max_length=20),
        ),
    ]
